[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on   = "t"
run  = "plugin --sync smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin --sync smart-enter"
# For upcoming Yazi 0.4 (nightly version):
# run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "A" 
run = "create --dir"
desc = "Create a directory"

