[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "go to the Pictures Directory"

[[mgr.prepend_keymap]]
on   = [ "g", "k" ]
run  = "cd ~/Documents"
desc = "go to the Documents Directory"

[[mgr.prepend_keymap]]
on   = [ "g", "f" ]
run  = "cd ~/dotfiles"
desc = "go to the Dotfiles Directory"

[[mgr.prepend_keymap]]
on = "A" 
run = "create --dir"
desc = "Create a directory"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

