-- Neovim 0.12+ has built-in treesitter support (no nvim-treesitter plugin needed)
-- Bundled parsers: c, lua, markdown, markdown_inline, query, vim, vimdoc
-- Highlighting is enabled automatically by Neovim's ftplugin system
